import { type ReactNode } from "react";
import { PublicLayout } from "@/components/public-layout";
import { Link } from "wouter";

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-base font-semibold">{title}</h2>
      <div className="text-muted-foreground leading-relaxed space-y-3 text-sm">{children}</div>
    </section>
  );
}

export default function Terms() {
  return (
    <PublicLayout>
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Use</h1>
        <p className="text-xs text-muted-foreground mb-12">Last updated: June 2026</p>

        <div className="space-y-10">
          <Section title="Acceptance">
            <p>
              By using Signal87 AI, you agree to these Terms of Use. If you do not agree, please do not use the service.
            </p>
          </Section>

          <Section title="What Signal87 AI is">
            <p>
              Signal87 AI is a document intelligence tool that lets you upload files, preview them, and ask AI-powered questions about their content. It is provided for informational and research purposes. It is <strong className="text-foreground">not</strong> a legal, financial, medical, or professional advisory service, and no content generated by the service should be treated as such.
            </p>
          </Section>

          <Section title="Your content">
            <p>
              You retain ownership of any documents you upload. By uploading a document, you confirm that you have the right to share its contents with the service and to send excerpts from it to our AI provider (OpenAI) in order to generate responses.
            </p>
            <p>
              Do not upload documents that contain other people's personal information without their consent, confidential information you are not authorized to disclose, or any content that is illegal or harmful.
            </p>
          </Section>

          <Section title="AI limitations">
            <p>
              Responses are generated by a large language model (Gemini). AI-generated answers can be incomplete, inaccurate, or misleading — even when they cite a source passage. Always verify important information against the original document and consult a qualified professional for decisions with legal, financial, or medical consequences.
            </p>
            <p>
              Citations indicate which passages were retrieved to inform a response. They are not a guarantee that the answer is accurate or complete.
            </p>
          </Section>

          <Section title="Acceptable use">
            <p>You agree not to use Signal87 AI to:</p>
            <ul className="space-y-1.5 list-disc list-inside mt-2">
              <li>Upload or process content that is illegal, defamatory, or that violates others' rights</li>
              <li>Attempt to reverse-engineer, overload, or otherwise abuse the service or its underlying infrastructure</li>
              <li>Generate content intended to deceive, harass, or harm other people</li>
              <li>Circumvent any access controls or security measures</li>
            </ul>
          </Section>

          <Section title="Service availability">
            <p>
              Signal87 AI is in early access and is provided without uptime guarantees. We may modify, limit, suspend, or discontinue the service at any time. We will make reasonable efforts to give advance notice of significant changes.
            </p>
          </Section>

          <Section title="Limitation of liability">
            <p>
              To the fullest extent permitted by applicable law, Signal87 AI and its operators are not liable for any direct, indirect, incidental, special, or consequential damages arising from your use of — or inability to use — the service, or from your reliance on any AI-generated output. The service is provided "as is" without warranty of any kind. Use it at your own risk.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions about these terms? Reach us at the{" "}
              <Link href="/contact" className="text-primary hover:underline">Contact page</Link>{" "}
              or by email at{" "}
              <a href="mailto:contact@signal87.ai" className="text-primary hover:underline">
                contact@signal87.ai
              </a>
              .
            </p>
          </Section>
        </div>
      </div>
    </PublicLayout>
  );
}
